import { sequelize } from "../config/db";
import Championship from "../models/championship";
import defaultAgeInterval from "../models/defaultAgeInterval";
import DefaultCategory from "../models/defaultCategory";
import DefaultDivision from "../models/defaultDivision";

//Campeonato
(async () => {
  try {
    await sequelize.sync();
    await Championship.bulkCreate([
      {
        championshipName: "Campeonato 01",
        organizer: "R4shad",
        organizerCi: 7920880,
        organizerPassword: "R4shad",
        championshipDate: "04/04/2024",
      },
    ]);

    console.log("Datos insertados correctamente.");
  } catch (error) {
    console.error("Error al insertar datos:", error);
  } finally {
    await sequelize.close(); // Cierra la conexión a la base de datos al finalizar
  }
})();
//Age interval
(async () => {
  try {
    await sequelize.sync(); // Sincroniza el modelo con la base de datos, eliminando las tablas existentes si existen
    await defaultAgeInterval.bulkCreate([
      {
        id: 1,
        ageIntervalName: "PreInfantilesA",
        minAge: 4,
        maxAge: 5,
      },
      {
        id: 2,
        ageIntervalName: "PreInfantilesB",
        minAge: 6,
        maxAge: 7,
      },
      {
        id: 3,
        ageIntervalName: "PreInfantilesC",
        minAge: 8,
        maxAge: 9,
      },
      {
        id: 4,
        ageIntervalName: "Infantiles",
        minAge: 10,
        maxAge: 11,
      },
      {
        id: 5,
        ageIntervalName: "Cadetes",
        minAge: 12,
        maxAge: 14,
      },
      {
        id: 6,
        ageIntervalName: "Juveniles",
        minAge: 15,
        maxAge: 17,
      },
      {
        id: 7,
        ageIntervalName: "Mayores",
        minAge: 18,
        maxAge: 100,
      },
    ]);
    console.log("Datos insertados correctamente.");
  } catch (error) {
    console.error("Error al insertar datos:", error);
  } finally {
    await sequelize.close(); // Cierra la conexión a la base de datos al finalizar
  }
})();
//Categorias
(async () => {
  try {
    await sequelize.sync(); // Sincroniza el modelo con la base de datos, eliminando las tablas existentes si existen
    await DefaultCategory.bulkCreate([
      {
        categoryName: "Avanzado",
        gradeMin: "rojo",
        gradeMax: "negro",
      },
      {
        categoryName: "Inicial",
        gradeMin: "franja amarillo",
        gradeMax: "franja verde",
      },
      {
        categoryName: "Intermedio",
        gradeMin: "verde",
        gradeMax: "franja rojo",
      },
    ]); // Omitir timestamps

    console.log("Datos insertados correctamente.");
  } catch (error) {
    console.error("Error al insertar datos:", error);
  } finally {
    await sequelize.close(); // Cierra la conexión a la base de datos al finalizar
  }
})();
//Division
(async () => {
  try {
    await sequelize.sync();
    await DefaultDivision.bulkCreate([
      {
        divisionName: "PreInfantilesA M1",
        ageIntervalId: 1,
        minWeight: 0,
        maxWeight: 19,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M2",
        ageIntervalId: 1,
        minWeight: 19,
        maxWeight: 21,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M3",
        ageIntervalId: 1,
        minWeight: 21,
        maxWeight: 23,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M4",
        ageIntervalId: 1,
        minWeight: 23,
        maxWeight: 25,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M5",
        ageIntervalId: 1,
        minWeight: 25,
        maxWeight: 27,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M6",
        ageIntervalId: 1,
        minWeight: 27,
        maxWeight: 30,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M7",
        ageIntervalId: 1,
        minWeight: 30,
        maxWeight: 33,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M8",
        ageIntervalId: 1,
        minWeight: 33,
        maxWeight: 36,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M9",
        ageIntervalId: 1,
        minWeight: 36,
        maxWeight: 39,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA M10",
        ageIntervalId: 1,
        minWeight: 39,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "PreInfantilesA",
      },

      {
        divisionName: "PreInfantilesA F1",
        ageIntervalId: 1,
        minWeight: 0,
        maxWeight: 19,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F2",
        ageIntervalId: 1,
        minWeight: 19,
        maxWeight: 21,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F3",
        ageIntervalId: 1,
        minWeight: 21,
        maxWeight: 23,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F4",
        ageIntervalId: 1,
        minWeight: 23,
        maxWeight: 25,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F5",
        ageIntervalId: 1,
        minWeight: 25,
        maxWeight: 27,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F6",
        ageIntervalId: 1,
        minWeight: 27,
        maxWeight: 30,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F7",
        ageIntervalId: 1,
        minWeight: 30,
        maxWeight: 33,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F8",
        ageIntervalId: 1,
        minWeight: 33,
        maxWeight: 36,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F9",
        ageIntervalId: 1,
        minWeight: 36,
        maxWeight: 39,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },
      {
        divisionName: "PreInfantilesA F10",
        ageIntervalId: 1,
        minWeight: 39,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "PreInfantilesA",
      },

      {
        divisionName: "PreInfantilesB M1",
        ageIntervalId: 2,
        minWeight: 0,
        maxWeight: 23,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M2",
        ageIntervalId: 2,
        minWeight: 23,
        maxWeight: 25,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M3",
        ageIntervalId: 2,
        minWeight: 25,
        maxWeight: 27,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M4",
        ageIntervalId: 2,
        minWeight: 27,
        maxWeight: 29,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M5",
        ageIntervalId: 2,
        minWeight: 29,
        maxWeight: 31,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M6",
        ageIntervalId: 2,
        minWeight: 31,
        maxWeight: 34,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M7",
        ageIntervalId: 2,
        minWeight: 34,
        maxWeight: 37,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M8",
        ageIntervalId: 2,
        minWeight: 37,
        maxWeight: 40,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M9",
        ageIntervalId: 2,
        minWeight: 40,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB M10",
        ageIntervalId: 2,
        minWeight: 43,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "PreInfantilesB",
      },

      {
        divisionName: "PreInfantilesB F1",
        ageIntervalId: 2,
        minWeight: 0,
        maxWeight: 23,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F2",
        ageIntervalId: 2,
        minWeight: 23,
        maxWeight: 25,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F3",
        ageIntervalId: 2,
        minWeight: 25,
        maxWeight: 27,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F4",
        ageIntervalId: 2,
        minWeight: 27,
        maxWeight: 29,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F5",
        ageIntervalId: 2,
        minWeight: 29,
        maxWeight: 31,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F6",
        ageIntervalId: 2,
        minWeight: 31,
        maxWeight: 34,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F7",
        ageIntervalId: 2,
        minWeight: 34,
        maxWeight: 37,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F8",
        ageIntervalId: 2,
        minWeight: 37,
        maxWeight: 40,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F9",
        ageIntervalId: 2,
        minWeight: 40,
        maxWeight: 43,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },
      {
        divisionName: "PreInfantilesB F10",
        ageIntervalId: 2,
        minWeight: 43,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "PreInfantilesB",
      },

      {
        divisionName: "PreInfantilesC  M1",
        ageIntervalId: 3,
        minWeight: 0,
        maxWeight: 25,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M2",
        ageIntervalId: 3,
        minWeight: 25,
        maxWeight: 27,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M3",
        ageIntervalId: 3,
        minWeight: 27,
        maxWeight: 29,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M4",
        ageIntervalId: 3,
        minWeight: 29,
        maxWeight: 31,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M5",
        ageIntervalId: 3,
        minWeight: 31,
        maxWeight: 33,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M6",
        ageIntervalId: 3,
        minWeight: 33,
        maxWeight: 36,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M7",
        ageIntervalId: 3,
        minWeight: 36,
        maxWeight: 39,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M8",
        ageIntervalId: 3,
        minWeight: 39,
        maxWeight: 42,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M9",
        ageIntervalId: 3,
        minWeight: 42,
        maxWeight: 45,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC M10",
        ageIntervalId: 3,
        minWeight: 45,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "PreInfantilesC",
      },

      {
        divisionName: "PreInfantilesC F1",
        ageIntervalId: 3,
        minWeight: 0,
        maxWeight: 25,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F2",
        ageIntervalId: 3,
        minWeight: 25,
        maxWeight: 27,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F3",
        ageIntervalId: 3,
        minWeight: 27,
        maxWeight: 29,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F4",
        ageIntervalId: 3,
        minWeight: 29,
        maxWeight: 31,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F5",
        ageIntervalId: 3,
        minWeight: 31,
        maxWeight: 33,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F6",
        ageIntervalId: 3,
        minWeight: 33,
        maxWeight: 36,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F7",
        ageIntervalId: 3,
        minWeight: 36,
        maxWeight: 39,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F8",
        ageIntervalId: 3,
        minWeight: 39,
        maxWeight: 42,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F9",
        ageIntervalId: 3,
        minWeight: 42,
        maxWeight: 45,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },
      {
        divisionName: "PreInfantilesC F10",
        ageIntervalId: 3,
        minWeight: 45,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "PreInfantilesC",
      },

      {
        divisionName: "Infantiles M1",
        ageIntervalId: 4,
        minWeight: 0,
        maxWeight: 27,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M2",
        ageIntervalId: 4,
        minWeight: 27,
        maxWeight: 30,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M3",
        ageIntervalId: 4,
        minWeight: 30,
        maxWeight: 33,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M4",
        ageIntervalId: 4,
        minWeight: 33,
        maxWeight: 36,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M5",
        ageIntervalId: 4,
        minWeight: 36,
        maxWeight: 39,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M6",
        ageIntervalId: 4,
        minWeight: 39,
        maxWeight: 42,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M7",
        ageIntervalId: 4,
        minWeight: 42,
        maxWeight: 45,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M8",
        ageIntervalId: 4,
        minWeight: 45,
        maxWeight: 48,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M9",
        ageIntervalId: 4,
        minWeight: 48,
        maxWeight: 51,
        gender: "Masculino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles M10",
        ageIntervalId: 4,
        minWeight: 51,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "Infantiles",
      },

      {
        divisionName: "Infantiles F1",
        ageIntervalId: 4,
        minWeight: 0,
        maxWeight: 27,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F2",
        ageIntervalId: 4,
        minWeight: 27,
        maxWeight: 30,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F3",
        ageIntervalId: 4,
        minWeight: 30,
        maxWeight: 33,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F4",
        ageIntervalId: 4,
        minWeight: 33,
        maxWeight: 36,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F5",
        ageIntervalId: 4,
        minWeight: 36,
        maxWeight: 39,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F6",
        ageIntervalId: 4,
        minWeight: 39,
        maxWeight: 42,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F7",
        ageIntervalId: 4,
        minWeight: 42,
        maxWeight: 45,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F8",
        ageIntervalId: 4,
        minWeight: 45,
        maxWeight: 48,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F9",
        ageIntervalId: 4,
        minWeight: 48,
        maxWeight: 51,
        gender: "Femenino",
        grouping: "Infantiles",
      },
      {
        divisionName: "Infantiles F10",
        ageIntervalId: 4,
        minWeight: 51,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "Infantiles",
      },

      {
        divisionName: "Cadetes M1",
        ageIntervalId: 5,
        minWeight: 0,
        maxWeight: 33,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M2",
        ageIntervalId: 5,
        minWeight: 33,
        maxWeight: 37,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M3",
        ageIntervalId: 5,
        minWeight: 37,
        maxWeight: 41,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M4",
        ageIntervalId: 5,
        minWeight: 41,
        maxWeight: 45,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M5",
        ageIntervalId: 5,
        minWeight: 45,
        maxWeight: 49,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M6",
        ageIntervalId: 5,
        minWeight: 49,
        maxWeight: 53,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M7",
        ageIntervalId: 5,
        minWeight: 53,
        maxWeight: 57,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M8",
        ageIntervalId: 5,
        minWeight: 57,
        maxWeight: 61,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M9",
        ageIntervalId: 5,
        minWeight: 61,
        maxWeight: 65,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes M10",
        ageIntervalId: 5,
        minWeight: 65,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F1",
        ageIntervalId: 5,
        minWeight: 0,
        maxWeight: 29,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F2",
        ageIntervalId: 5,
        minWeight: 29,
        maxWeight: 33,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F3",
        ageIntervalId: 5,
        minWeight: 33,
        maxWeight: 37,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F4",
        ageIntervalId: 5,
        minWeight: 37,
        maxWeight: 41,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F5",
        ageIntervalId: 5,
        minWeight: 41,
        maxWeight: 44,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F6",
        ageIntervalId: 5,
        minWeight: 44,
        maxWeight: 47,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F7",
        ageIntervalId: 5,
        minWeight: 47,
        maxWeight: 51,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F8",
        ageIntervalId: 5,
        minWeight: 51,
        maxWeight: 55,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F9",
        ageIntervalId: 5,
        minWeight: 55,
        maxWeight: 59,
        gender: "Femenino",
        grouping: "Cadetes",
      },
      {
        divisionName: "Cadetes F10",
        ageIntervalId: 5,
        minWeight: 49,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "Cadetes",
      },

      {
        divisionName: "Juveniles M1",
        ageIntervalId: 6,
        minWeight: 0,
        maxWeight: 45,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M2",
        ageIntervalId: 6,
        minWeight: 45,
        maxWeight: 48,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M3",
        ageIntervalId: 6,
        minWeight: 48,
        maxWeight: 51,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M4",
        ageIntervalId: 6,
        minWeight: 51,
        maxWeight: 55,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M5",
        ageIntervalId: 6,
        minWeight: 55,
        maxWeight: 59,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M6",
        ageIntervalId: 6,
        minWeight: 59,
        maxWeight: 63,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M7",
        ageIntervalId: 6,
        minWeight: 63,
        maxWeight: 68,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M8",
        ageIntervalId: 6,
        minWeight: 68,
        maxWeight: 73,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M9",
        ageIntervalId: 6,
        minWeight: 73,
        maxWeight: 78,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles M10",
        ageIntervalId: 6,
        minWeight: 78,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F1",
        ageIntervalId: 6,
        minWeight: 0,
        maxWeight: 42,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F2",
        ageIntervalId: 6,
        minWeight: 42,
        maxWeight: 44,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F3",
        ageIntervalId: 6,
        minWeight: 44,
        maxWeight: 46,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F4",
        ageIntervalId: 6,
        minWeight: 46,
        maxWeight: 49,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F5",
        ageIntervalId: 6,
        minWeight: 49,
        maxWeight: 52,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F6",
        ageIntervalId: 6,
        minWeight: 52,
        maxWeight: 55,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F7",
        ageIntervalId: 6,
        minWeight: 55,
        maxWeight: 59,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F8",
        ageIntervalId: 6,
        minWeight: 59,
        maxWeight: 63,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F9",
        ageIntervalId: 6,
        minWeight: 63,
        maxWeight: 68,
        gender: "Femenino",
        grouping: "Juveniles",
      },
      {
        divisionName: "Juveniles F10",
        ageIntervalId: 6,
        minWeight: 68,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "Juveniles",
      },

      {
        divisionName: "Mayores F1",
        ageIntervalId: 7,
        minWeight: 0,
        maxWeight: 49,
        gender: "Femenino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores F2",
        ageIntervalId: 7,
        minWeight: 49,
        maxWeight: 57,
        gender: "Femenino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores F3",
        ageIntervalId: 7,
        minWeight: 57,
        maxWeight: 67,
        gender: "Femenino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores F4",
        ageIntervalId: 7,
        minWeight: 67,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores M1",
        ageIntervalId: 7,
        minWeight: 0,
        maxWeight: 58,
        gender: "Masculino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores M2",
        ageIntervalId: 7,
        minWeight: 58,
        maxWeight: 68,
        gender: "Masculino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores M3",
        ageIntervalId: 7,
        minWeight: 68,
        maxWeight: 80,
        gender: "Masculino",
        grouping: "Mayores Olímpicos",
      },
      {
        divisionName: "Mayores M4",
        ageIntervalId: 7,
        minWeight: 80,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "Mayores Olímpicos",
      },

      {
        divisionName: "Mayores F1",
        ageIntervalId: 7,
        minWeight: 0,
        maxWeight: 46,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F2",
        ageIntervalId: 7,
        minWeight: 46,
        maxWeight: 49,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F3",
        ageIntervalId: 7,
        minWeight: 49,
        maxWeight: 53,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F4",
        ageIntervalId: 7,
        minWeight: 53,
        maxWeight: 57,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F5",
        ageIntervalId: 7,
        minWeight: 57,
        maxWeight: 62,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F6",
        ageIntervalId: 7,
        minWeight: 62,
        maxWeight: 67,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F7",
        ageIntervalId: 7,
        minWeight: 67,
        maxWeight: 73,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores F8",
        ageIntervalId: 7,
        minWeight: 73,
        maxWeight: 100,
        gender: "Femenino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M1",
        ageIntervalId: 7,
        minWeight: 0,
        maxWeight: 54,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M2",
        ageIntervalId: 7,
        minWeight: 54,
        maxWeight: 58,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M3",
        ageIntervalId: 7,
        minWeight: 58,
        maxWeight: 63,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M4",
        ageIntervalId: 7,
        minWeight: 63,
        maxWeight: 68,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M5",
        ageIntervalId: 7,
        minWeight: 68,
        maxWeight: 74,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M6",
        ageIntervalId: 7,
        minWeight: 74,
        maxWeight: 80,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M7",
        ageIntervalId: 7,
        minWeight: 80,
        maxWeight: 87,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
      {
        divisionName: "Mayores M8",
        ageIntervalId: 7,
        minWeight: 87,
        maxWeight: 100,
        gender: "Masculino",
        grouping: "Mayores Mundiales",
      },
    ]);
    console.log("Datos insertados correctamente.");
  } catch (error) {
    console.error("Error al insertar datos:", error);
  } finally {
    await sequelize.close();
  }
})();
